### ISSUE TITLE
Open Street View

### ISSUE THREAD

**Issue by jadonald-s1** [istarkov/google-map-react#251]
I can see that there is a way to add the pegman to the control, but is there a way to open streetview by default instead of the map?

**Comment by peitalin** [comment]
You could use `onGoogleApiLoaded` to load StreetView by default. In your react component write a method to call:
`
    initStreetView({map, maps}) {
        var sv = new maps.StreetViewService();
        var panorama = new maps.StreetViewPanorama(document.getElementById('map'));
        sv.getPanorama({location: {lat: 37.869, lng: -122.254}, radius: 50}, processSVData);

        function processSVData(data, status) {
            var marker = new maps.Marker({
                position: data.location.latLng,
                map: map,
                title: data.location.description
            });
            panorama.setPano(data.location.pano)
            panorama.setPov({
                heading: 270,
                pitch: 0
            });
            panorama.setVisible(true);
        }
    }
`

Which you can call after Google API loads:
`<GoogleMap bootstrapURLKeys={{key: APIKEY}} onGoogleApiLoaded={this.initStreetView} />`

**Comment by anthonyvialleton** [comment]
Implementing this solution works but we got this console error log : 

`js?callback=_$_google_map_initialize_$_&key=:42 Uncaught TypeError: Cannot read property 'style' of null
    at new _.hw (https://maps.googleapis.com/maps-api-v3/api/js/27/4/intl/fr_ALL/common.js:186:165)
    at x3 (https://maps.googleapis.com/maps-api-v3/api/js/27/4/intl/fr_ALL/streetview.js:81:497)
    at Object._.k.cn (https://maps.googleapis.com/maps-api-v3/api/js/27/4/intl/fr_ALL/streetview.js:148:133)
    at https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=:115:2696
    at Object._.F (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=:48:454)
    at rf.visible_changed (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=:115:2648)
    at Ab (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=:40:342)
    at rf._.k.set (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=:99:735)
    at rf.setVisible (https://maps.googleapis.com/maps/api/js?callback=_$_google_map_initialize_$_&key=:50:342)
    at processSVData (eval at <anonymous> (http://192.168.4.120:8050/static/build/dev/main.js:3886:2), <anonymous>:318:26)
    at rm.T2 (https://maps.googleapis.com/maps-api-v3/api/js/27/4/intl/fr_ALL/streetview.js:55:251)
    at rm.Cn (https://maps.googleapis.com/maps-api-v3/api/js/27/4/intl/fr_ALL/common.js:26:185)
    at Object.c [as _xeisu0] (https://maps.googleapis.com/maps-api-v3/api/js/27/4/intl/fr_ALL/common.js:44:404)
    at https://maps.googleapis.com/maps/api/js/GeoPhotoService.SingleImageSearch?p…2!4m10!1e1!1e2!1e3!1e4!1e8!1e6!5m1!1e2!6m1!1e2&callback=_xdc_._xeisu0:1:28_.hw @ common.js:186x3 @ streetview.js:81_.k.cn @ streetview.js:148(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:115_.F @ js?callback=_$_google_map_initialize_$_&key=:48rf.visible_changed @ js?callback=_$_google_map_initialize_$_&key=:115Ab @ js?callback=_$_google_map_initialize_$_&key=:40_.k.set @ js?callback=_$_google_map_initialize_$_&key=:99(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:50processSVData @ OverviewPage.jsx?28f6:277T2 @ streetview.js:55(anonymous function) @ common.js:26c @ common.js:44(anonymous function) @ GeoPhotoService.SingleImageSearch?pb=!1m5!1sapiv3!5sUS!11m2!1m1!1b0!2m4!1m2!3d37.869!4d-122.2547000…:1
util.js:211 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keysWA.j @ util.js:211(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:129(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:49(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:46(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:49_.F @ js?callback=_$_google_map_initialize_$_&key=:48(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:49_.v @ js?callback=_$_google_map_initialize_$_&key=:34mc @ js?callback=_$_google_map_initialize_$_&key=:49(anonymous function) @ js?callback=_$_google_map_initialize_$_&key=:129`

This problem seems to be due to the map div not being rendered before the javascript runs that needs to access it.

**Comment by anthonyvialleton** [comment]
up ?

**Comment by acharlop** [comment]
Any answer for this? I'm just getting started with the package and need this functionality.

**Comment by istarkov** [comment]
It is not the intent of this library to support every part of google map API, my life is to short for this ;-)
Please read first sentences in READMe. 

So just check the proposed solution from above or use google map api directly if it does not work for some reason.

**Comment by MirkoAlo** [comment]
We know that your life is too short for this, but the ask of jadonald72 is very important, the streetview is a important part of google map

**Comment by itsmichaeldiego** [comment]
@MirkoAlo I think what @istarkov wanted to say in cute words is that, this library was made to speed up the development when using GoogleMaps, but we don't support all the features as this was built on-the-go from our users!

When a user wants a feature, they normally contribute to our library and that is how community works, I help you, you help me or others by adding the features some other users might need as you do... 

Libraries are made in order to help other developers but it is not mandatory for us to create a library that fits all _your_ needs, so I encourage you guys to contribute to our project so we grow together, instead of requesting other people to build features that _you_ need for _your_ work.

Thanks in advance <3

**Comment by MirkoAlo** [comment]
Yes i know... Sorry form my ask!
Otherwise i found a solution! 

const google = window.google;   ( for not return undefined )

**Comment by itsmichaeldiego** [comment]
@MirkoAlo That is good, I am glad you found out how to do it. I think you have a better way to do it while using _onGoogleApiLoaded_, somethine like:

```
const GoogleMap = props => (
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: YOUR_KEY,
      language: 'en',
    }}
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, props.places)}
  >
    {props.children}
  </GoogleMapReact>
);
```

```
const apiIsLoaded = (map, maps) => {
  if (map) {
    const panorama = maps.StreetViewPanorama(
      this.refs.panorama, {
        position: { lat: -34.397, lng: 150.644 },
        pov: {
          heading: 34,
          pitch: 10,
        },
      });

    map.setStreetView(panorama);
  }
};
```

**Comment by brianlaw033** [comment]
may I know where did u get `this.refs.panorama`?
I tried
```
<GoogleMap
        ref={'panorama'}
        {...others}
/>
```

but not working
