### ISSUE TITLE
Cannot find module 'react-dom'

### ISSUE THREAD

**Issue by alaghband** [istarkov/google-map-react#281]
Hello, I am fairly new to react. When I install this project and run my project, I get the following error:

module.js:474
    throw err;
    ^

Error: Cannot find module 'react-dom'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

I guess line 15 of the google_map.js file is causing this:
var _reactDom = require('react-dom');

Any clues how I should fix this? Thanks!

**Comment by istarkov** [comment]
It's on you to install `react` and `react-dom` npm packages. 

Also looks like it's needed to add `react-dom` into peer dependencies in this lib https://github.com/istarkov/google-map-react/blob/master/package.json#L40

**Comment by alaghband** [comment]
Thanks. I understand that I may be doing something silly here, and I have of course installed react-dom, but nothing seems to work. I have actually tried all the fixes that I could come up with (e.g. adding packages, deleting node_modules and re-running npm install, etc.), but I always get a module-related error. 

In particular, I am not sure why npm install google-map-react --save doesn't automatically install of all its dependencies (including react-dom). 

FYI, after manually installing react-dom:

npm install react-dom --save

I get this error:

module.js:474
    throw err;
    ^

Error: Cannot find module 'react/lib/ReactComponentTreeHook'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
