### ISSUE TITLE
addComponentAsRefTo

### ISSUE THREAD

**Issue by RishabhJain96** [istarkov/google-map-react#325]
It seems like google map react is attempting to use another version of React. I'm getting the following error:

> Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

**Comment by istarkov** [comment]
this lib supports 0.14.* and 15.* react versions,
and having a lot of code examples Im pretty surre the problem not in this library.
Seems like u need to do clean npm install
```
rm -rf node_modules && npm install
```

**Comment by RishabhJain96** [comment]
Does not fix the issue.

It is possible that it is due to my lerna setup; however, no other library breaks in this manner.

**Comment by istarkov** [comment]
There are a lot of examples refs in README and all of them works as expected. 
I use it in a lot of projects with react 0.14 and 15 and see no issues.
I have no idea whats wrong with your setup.

**Comment by jopdeklein** [comment]
I am having the same issue, when I clone the project and install npm dependencies I get the following error:
```
[kotatsu] ./develop/Main.js
Module parse failed: /google-map-react/develop/Main.js Unexpected token (17:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (17:2)
    at Parser.pp$4.raise (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/google-map-react/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
 @ multi main
```

```
> node -v
v7.5.0
```

**Comment by istarkov** [comment]
@jopdeklein How unexpected token could be the same issue? ;-) Have you read an issue description?

I've just checked library with clean install on latest node 7.7.1

```shell
rm -rf node_modules
npm install
npm run start
# open localhost:4000
```
All is working as expected. I'm pretty sure that you have or global npm-babel settings pollution or just executed some unknown command.

**Comment by jopdeklein** [comment]
@istarkov I must've read that wrong, apologies. I will try again and create a separate issue if needed.

**Comment by jopdeklein** [comment]
@istarkov I see I've pasted the wrong output :) I am also experiencing the `addComponentAsRefTo` error, will try to isolate and get back to you.

**Comment by itsmichaeldiego** [comment]
Please try with latest version and open a new issue if the problem persists.
